version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_dev
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    networks:
      - dev_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_dev
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - dev_network

  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
