FROM openjdk:17
ARG JAR_FILE=build/libs/*.jar
ARG JASYPT_ENCRYPTOR_PASSWORD
ARG FIREBASE_CONFIG
ENV JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
