spring:
  config:
    activate:
      on-profile: prod
    import: "classpath:application-infra-prod.yml"

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(AHsyxM9A8g8wHiYs1Ao7S5Lrtcuqe6E5VX5dMUTeKyZnDULppD99ZrtY10al3wgruDWWWaKEcify/hBgQ4xxzEpH6fG4Vf2MnuN6IVzMU8X6VLDbW1EI8KjC9cY6gOfl)
    url: ENC(VUc1Yhm/R97MdPeKVapaqBwHudKRJbBY7XsC9r0O8ZRKEng/6uHGHcgPT9oGoKzm7WlqVmmIPl3H7BJ7yJQd0uTg3KaTli5sDWdwInHHpHNQY+xUSXH1qadnb1R5DaNr)
    username: ENC(dEU2P1q9Gh22al1j0nQOGMS4c6TBMnN3)
    password: ENC(OQXOXZaAaMtwqzKjRQoiAgdVeOe2/GmJ)
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 20MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: ENC(wvHQPgB402IXW85HHlu4kOAwZWKIrG37GCmHPa2CIoo0vMefVWzmRa1rEHNwzMWH)
        default_batch_fetch_size: ENC(vlfxBKZ6fXmAzqpH/OcG6A==)

  kafka:
    bootstrap-servers: kafka:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    properties:
      delivery.timeout.ms: 5000  # 메시지 최대 전달 시간
      request.timeout.ms: 5000    # 브로커 응답 대기 시간
      linger.ms: 0                # 메시지 즉시 전송
      max.block.ms: 5000         # 최대 차단 시간
      reconnect.backoff.ms: 1000  # 재연결 최소 대기 시간
      reconnect.backoff.max.ms: 5000  # 재연결 최대 대기 시간


kafka:
  topic:
    notification: notification-topic
    internal:
      error: exception-topic
logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO