logging:
    level:
        org:
            springframework:
                security: DEBUG

server:
    tomcat:
        uri-encoding: UTF-8

spring:
    jackson:
        time-zone: Asia/Seoul
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ENC(WFk66f1yW1ScePrjVXtNkD583lPA22lCf8CKSAtjoWJgYPBKvmDweiOoifK559d+2Eynoz1Gy1yZKATTQGW4ww+ggSzJ5CslVQ07NsH8AtyGHAmmpz/L2m052TZprgvy)
        username: ENC(nDVimcgDVyy1KRjg2ctKjQ==)
        password: ENC(3SMxxiwN0hQ0QXvt9r24HMf5U+nQk8lc)
        hikari:
            data-source-properties:
                serverTimezone: Asia/Seoul

    servlet:
        multipart:
            max-file-size: 20MB

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: ENC(wvHQPgB402IXW85HHlu4kOAwZWKIrG37GCmHPa2CIoo0vMefVWzmRa1rEHNwzMWH)
                default_batch_fetch_size: ENC(vlfxBKZ6fXmAzqpH/OcG6A==)



    mail:
        host: smtp.gmail.com
        port: 587
        sender-email: ENC(XY41e1DCUH9AsqGoXILdUTLQRIFNRRmG4YjJRNwOzBQOiP+2tkUFSg==)
        password: ENC(2gk/TTxPHgwJb1UuomrSKXxtToyzjO+Yo4qa9YGsjPQ=)
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    timeout: 5000
    #            auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

    data:
        redis:
            host: ENC(1xiKDNpnqSNdYDm2jh+IBCc/qdE8rDG1s3cw34Aah8N23+oojr+oSlYjRxeH1pobQthJcPfUbJ5+udWBbH0HGF3njvj5ygD3)
            port: 6379

cloud:
    aws:
        credentials:
            accessKey: ENC(SJv3Q6Kya+e0vv90IUu10KEptIU2OPtBRrDngS+2VEk=)
            secretKey: ENC(PPxIknKNn+UJfvNSV3l4lH84FIio3m9SgReMhSQDgC+IBWz9FiT26HG372CzSxum749+Z9GLIEA=)
        region:
            static: ap-northeast-2
        s3:
            bucket: ENC(o/ib/PhYeF9khIBN1TIJt1+tTlBEELR0)
            dirname: ENC(qQBWAF+TGWVncxA4oIdEaxoCC8WOsJyt)

jwt:
    secret:
        key: ENC(KR2DiPWemDkz0qiwysKkyKTzfAZ3xn+xfQGcfw0g/zsHsE+b+rjTIOCOt2W490X8ZqvybLfmzvHn1wx6EhmBbFbJ9TDYGbWsElOu3nNvJ49Gtnl2l/uwU4oScdbH1A/OsLIfISr+d2G3CpRpTyJmyAvzG1mVLkDEhTH6YBEJ1x2hfI+iBUQm9A==)

google:
    firebase:
        fcm:
            resource:
                path: ENC(1w5VOfwAxMMzT+R2d1hu2wGP/S59sFHUkr2EtKUPGYhAV3V2uCQkD0tURCrcwwhl)

jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}
