worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # 로그 설정
    error_log /var/log/nginx/error.log debug;

    # API 컨테이너에 대한 upstream 설정
    upstream api_upstream {
        server api:8080; # API 컨테이너 이름과 포트
    }

    # Grafana 컨테이너에 대한 upstream 설정
    upstream grafana_upstream {
        server grafana:3000; # Grafana 컨테이너 이름과 포트
    }

    upstream prometheus_upstream {
        server prometheus:9090; # Prometheus 컨테이너 이름과 포트
    }

    server {
        listen 80;

        # 일반 API 경로 처리
        location / {
            proxy_pass http://api_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Grafana 요청 처리
        location /monitoring-admin/ {
            proxy_pass http://grafana_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Grafana 장애 시 사용자 정의 메시지 반환
            proxy_intercept_errors on;
            error_page 502 = @grafana_down;
        }

        # Grafana 장애 시 처리
        location @grafana_down {
            return 503 "Grafana is unavailable. Please try again later.";
        }

        # Prometheus 요청 처리
        location /actuator/prometheus {
            proxy_pass http://api_upstream/actuator/prometheus; # API 컨테이너로 요청 전달
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;

            # Prometheus 장애 시 사용자 정의 메시지 반환
            proxy_intercept_errors on;
            error_page 502 = @prometheus_down;

            # CORS 헤더 추가
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
            add_header Access-Control-Allow-Headers "Authorization, Content-Type";
        }

        # Prometheus 장애 시 처리
        location @prometheus_down {
            return 503 "Prometheus is unavailable. Please try again later.";
        }
    }
}
